### ISSUE TITLE
On tags and scripts

### ISSUE THREAD

**Issue by jmohler1970** [adamcameron/cfml24h#13]
On the page https://github.com/adamcameron/cfml24h/blob/master/chapters/00-housekeeping.md,

There should be some minimal examples of what a cf tag looks like and what code inside of a <cfscript> looks like.

**Comment by adamcameron** [comment]
Yeah, good point.

**Comment by adamcameron** [comment]
Done: https://github.com/adamcameron/cfml24h/blob/master/chapters/00-housekeeping.md#cfml-tags-script-huh
