### ISSUE TITLE
Starter websites

### ISSUE THREAD

**Issue by jmohler1970** [adamcameron/cfml24h#19]
Languages such and Ruby and ASP.NET etc. all have very strong notions as to where files are supposed to exist. I know that ColdFusion allows for files go anywhere, but that is not a best practice.

I recently had to train some co-workers and it was very intimidating. I could not just hand them something to get started. I had to start with website with thousands of files. If could have handed them a 10 or 20 file "Hello world", things would have been simpler.

They want some code

**Comment by adamcameron** [comment]
Again, this book is not about web sites, it's about CFML.
