### ISSUE TITLE
FW/1 is on GitHub too

### ISSUE THREAD

**Issue by jmohler1970** [adamcameron/cfml24h#21]
For https://github.com/adamcameron/cfml24h/blob/master/chapters/12-mvc.md

The link to FW/1 is

Code:
https://github.com/framework-one/fw1

Blog:
http://framework-one.github.io/

**Comment by adamcameron** [comment]
You can just do a pull req for this stuff mate. Where the chapter is empty, just stick a section "notes", and put it in the doc itself. It can be tidied up later.
