### ISSUE TITLE
Custom tags for views

### ISSUE THREAD

**Issue by jmohler1970** [adamcameron/cfml24h#22]
https://github.com/adamcameron/cfml24h/blob/master/chapters/14-custom_tags.md

I have lots of custom tags for views:

https://github.com/jmohler1970/BS-4-CF/tree/master/views/_bootstrap

**Comment by adamcameron** [comment]
Cool, thanks for the thought. I had a look at a few but the ones I looked at were way to complicated for what they set out to do, and def too complicated for a document like this. And, TBH, not good examples of what one would generally want to use custom tags for,so I'd not want to encourage ppl looking at that stuff.

I've got some simple examples up my sleeve already. I should copy & paste 'em into the chapter file, I guess.
