### ISSUE TITLE
Esapi and public facing sites

### ISSUE THREAD

**Issue by jmohler1970** [adamcameron/cfml24h#23]
On public facing sites, protection against various attacks is very important. On a recent job interview, 50% of the interview time was on this topic:

http://blogs.adobe.com/security/2014/05/coldfusion-11-enhances-the-security-foundation-of-coldfusion-10.html
(Antisamy)

https://www.owasp.org/index.php/ColdFusion_Security_Resources

http://cfpavankumar.blogspot.com/2014/04/using-antisamy-framework-with.html

**Comment by adamcameron** [comment]
James, please read and absorb chapter 0 before filing any more "issues"

This is not a book about websites. It's a book about CFML.
