### ISSUE TITLE
 Name Change For Book << Semantics

### ISSUE THREAD

**Issue by shawnoden** [adamcameron/cfml24h#35]
If I'm reading the intent correctly, this isn't really meant to be a Learn CFML In 24 Hours book. This seems to be more Learn _Better_ CFML in 24 Hours. The "Learn X In 24 Hours" books are generally geared towards new or low-experience devs and include many of the basics. From what I understand here, this is meant more for devs who've already gotten their feet a bit wet in CF and want to learn better ways of doing things. 

I think a slight change of name would better illustrate the ultimate intent of this book. Unless I've read this incorrectly.

**Comment by adamcameron** [comment]
Yeah, I also think the "in 24 hours" thing is a (tm) of SAMS or whoever does those books using that description.

I think the name of the thing can wait until we see what the content is, and one can be picked based on that.
